@{
    Description   = 'This is the strings file for the Intune Helpdesk script. It contains all the user-facing strings used in the script.'
    deviceActions = @{
        contactAdmin     = 'Contact an Intune administrator'
        contactHelpdesk  = 'Contact the helpdesk'
        WipeOrClean      = 'Wipe or clean the device'
        connectToNetwork = 'Connect the device to a network'
        none             = 'No action'
    }
    deviceStates  = @{
        Ready    = 'The device is ready for the next user'
        NotReady = 'The device is not ready for the next user'
    }
    returnValues  = @{
        testUpdateMessage              = "Only Update tests. No update applied"
        backoutText                    = 'Returning to previous menu'
        deviceAssignmentPendingMessage = 'The device is pending assignment to a deployment profile.'
        '1003'                         = 'Updates failed to install'
        deviceDeleteSuccessMessage     = 'The device was deleted successfully.'
        noUserFoundInDirectoryMessage  = 'This user does not exist'
        deviceRestartFailedMessage     = 'The device restart failed.'
        UpdateCancelledMessage         = 'The update was cancelled.'
        noDeviceFound                  = 'No device found'
        UpdateNotNeededMessage         = 'The script is already up to date.'
        noBitLockerKeysFoundMessage    = 'No BitLocker keys found for this device.'
        deviceAssignedMessage          = 'The device is assigned to a deployment profile.'
        EnrollmentFailedMessage        = 'The device enrollment failed.'
        deviceCleanSuccessMessage      = 'The device was cleaned successfully.'
        invalidFileType                = 'Invalid file type.'
        '1000'                         = 'All updates were installed'
        InvalidFileHash                = 'The file hash is invalid. The update will be aborted.'
        noGroupFoundInDirectoryMessage = 'This group does not exist'
        noUserDeviceFoundMessage       = 'No user or device found.'
        noGroupAssignmentsFoundMessage = 'No assignments found for the specified group.'
        UpdateSuccessMessage           = 'The script was updated successfully.'
        deviceIsInIntuneMessage        = 'The device is in Intune. Delete the device and try again.'
        deviceSyncFailedMessage        = 'The device sync failed.'
        InvalidSignatureMessage        = 'The signature is invalid. The update will be aborted.'
        deviceUnknownActionMessage     = 'The action may still be in progress. You can check the device status in the Intune portal.'
        noRestartMessage               = 'Device not restarted.'
        userCanceledMessage            = 'Operation canceled by user'
        deviceNotAssignedMessage       = 'The device is not assigned to a deployment profile.'
        '999'                          = 'No updates were found'
        notContactedMessage            = 'The device has not contacted the enrollment service.'
        unknownErrorMessage            = 'An unknown error occurred.'
        manufacturerNotAllowed         = 'You are not allowed to import this device using this script.  Please contact your system administrator.'
        PendingResetMessage            = 'The device is pending a reset.'
        deviceRestartSuccessMessage    = 'The device was restarted successfully.'
        deviceWipeFailedMessage        = 'The device wipe failed.'
        '1001'                         = 'Some updates were installed'
        serialNumberNotFoundMessage    = 'The serial number was not found.'
        noLAPSFoundMessage             = 'No LAPS password found for this device.'
    }
}
