#
# Module manifest for module 'Microsoft.Graph.Groups'
#
# Generated by: Microsoft Corporation
#
# Generated on: 11/20/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Groups.psm1'

# Version number of this module.
ModuleVersion = '2.25.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '50bc9e18-e281-4208-8913-c9e1bef6083d'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.25.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Groups.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Groups.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgGroupDriveListContentTypeCopy', 
               'Add-MgGroupDriveListContentTypeCopyFromContentTypeHub', 
               'Add-MgGroupFavorite', 'Add-MgGroupSite', 
               'Add-MgGroupSiteContentTypeCopy', 
               'Add-MgGroupSiteContentTypeCopyFromContentTypeHub', 
               'Add-MgGroupSiteListContentTypeCopy', 
               'Add-MgGroupSiteListContentTypeCopyFromContentTypeHub', 
               'Add-MgGroupToLifecyclePolicy', 
               'Confirm-MgGroupGrantedPermissionForApp', 
               'Confirm-MgGroupMemberGroup', 'Confirm-MgGroupMemberObject', 
               'Confirm-MgGroupSettingTemplateMemberGroup', 
               'Confirm-MgGroupSettingTemplateMemberObject', 
               'Copy-MgGroupDriveItem', 
               'Copy-MgGroupDriveListContentTypeToDefaultContentLocation', 
               'Copy-MgGroupDriveRoot', 'Copy-MgGroupOnenoteNotebook', 
               'Copy-MgGroupOnenotePageToSection', 
               'Copy-MgGroupOnenoteSectionToNotebook', 
               'Copy-MgGroupOnenoteSectionToSectionGroup', 
               'Copy-MgGroupSiteContentTypeToDefaultContentLocation', 
               'Copy-MgGroupSiteListContentTypeToDefaultContentLocation', 
               'Get-MgAllGroupSite', 'Get-MgGroup', 'Get-MgGroupAcceptedSender', 
               'Get-MgGroupAcceptedSenderByRef', 'Get-MgGroupAcceptedSenderCount', 
               'Get-MgGroupById', 'Get-MgGroupByUniqueName', 
               'Get-MgGroupCalendarEventDelta', 'Get-MgGroupCalendarSchedule', 
               'Get-MgGroupConversation', 'Get-MgGroupConversationCount', 
               'Get-MgGroupConversationThread', 
               'Get-MgGroupConversationThreadCount', 
               'Get-MgGroupConversationThreadPost', 
               'Get-MgGroupConversationThreadPostAttachment', 
               'Get-MgGroupConversationThreadPostAttachmentCount', 
               'Get-MgGroupConversationThreadPostCount', 
               'Get-MgGroupConversationThreadPostExtension', 
               'Get-MgGroupConversationThreadPostExtensionCount', 
               'Get-MgGroupConversationThreadPostInReplyToAttachment', 
               'Get-MgGroupConversationThreadPostInReplyToAttachmentCount', 
               'Get-MgGroupConversationThreadPostInReplyToExtension', 
               'Get-MgGroupConversationThreadPostInReplyToExtensionCount', 
               'Get-MgGroupCount', 'Get-MgGroupCreatedOnBehalfOf', 
               'Get-MgGroupDelta', 'Get-MgGroupDriveItemActivityByInterval', 
               'Get-MgGroupDriveItemDelta', 
               'Get-MgGroupDriveItemListItemActivityByInterval', 
               'Get-MgGroupDriveListContentTypeCompatibleHubContentType', 
               'Get-MgGroupDriveListItemActivityByInterval', 
               'Get-MgGroupDriveListItemDelta', 
               'Get-MgGroupDriveRootActivityByInterval', 
               'Get-MgGroupDriveRootDelta', 
               'Get-MgGroupDriveRootListItemActivityByInterval', 
               'Get-MgGroupEventDelta', 'Get-MgGroupExtension', 
               'Get-MgGroupExtensionCount', 'Get-MgGroupLifecyclePolicy', 
               'Get-MgGroupLifecyclePolicyByGroup', 
               'Get-MgGroupLifecyclePolicyCount', 'Get-MgGroupMember', 
               'Get-MgGroupMemberAsApplication', 'Get-MgGroupMemberAsDevice', 
               'Get-MgGroupMemberAsGroup', 'Get-MgGroupMemberAsOrgContact', 
               'Get-MgGroupMemberAsServicePrincipal', 'Get-MgGroupMemberAsUser', 
               'Get-MgGroupMemberByRef', 'Get-MgGroupMemberCount', 
               'Get-MgGroupMemberCountAsApplication', 
               'Get-MgGroupMemberCountAsDevice', 'Get-MgGroupMemberCountAsGroup', 
               'Get-MgGroupMemberCountAsOrgContact', 
               'Get-MgGroupMemberCountAsServicePrincipal', 
               'Get-MgGroupMemberCountAsUser', 'Get-MgGroupMemberGroup', 
               'Get-MgGroupMemberObject', 'Get-MgGroupMemberOf', 
               'Get-MgGroupMemberOfAsAdministrativeUnit', 
               'Get-MgGroupMemberOfAsGroup', 'Get-MgGroupMemberOfCount', 
               'Get-MgGroupMemberOfCountAsAdministrativeUnit', 
               'Get-MgGroupMemberOfCountAsGroup', 
               'Get-MgGroupMemberWithLicenseError', 
               'Get-MgGroupMemberWithLicenseErrorAsApplication', 
               'Get-MgGroupMemberWithLicenseErrorAsDevice', 
               'Get-MgGroupMemberWithLicenseErrorAsGroup', 
               'Get-MgGroupMemberWithLicenseErrorAsOrgContact', 
               'Get-MgGroupMemberWithLicenseErrorAsServicePrincipal', 
               'Get-MgGroupMemberWithLicenseErrorAsUser', 
               'Get-MgGroupMemberWithLicenseErrorCount', 
               'Get-MgGroupMemberWithLicenseErrorCountAsApplication', 
               'Get-MgGroupMemberWithLicenseErrorCountAsDevice', 
               'Get-MgGroupMemberWithLicenseErrorCountAsGroup', 
               'Get-MgGroupMemberWithLicenseErrorCountAsOrgContact', 
               'Get-MgGroupMemberWithLicenseErrorCountAsServicePrincipal', 
               'Get-MgGroupMemberWithLicenseErrorCountAsUser', 
               'Get-MgGroupOnenoteNotebookFromWebUrl', 
               'Get-MgGroupOnenoteRecentNotebook', 'Get-MgGroupOwner', 
               'Get-MgGroupOwnerAsApplication', 'Get-MgGroupOwnerAsDevice', 
               'Get-MgGroupOwnerAsGroup', 'Get-MgGroupOwnerAsOrgContact', 
               'Get-MgGroupOwnerAsServicePrincipal', 'Get-MgGroupOwnerAsUser', 
               'Get-MgGroupOwnerByRef', 'Get-MgGroupOwnerCount', 
               'Get-MgGroupOwnerCountAsApplication', 
               'Get-MgGroupOwnerCountAsDevice', 'Get-MgGroupOwnerCountAsGroup', 
               'Get-MgGroupOwnerCountAsOrgContact', 
               'Get-MgGroupOwnerCountAsServicePrincipal', 
               'Get-MgGroupOwnerCountAsUser', 'Get-MgGroupPermissionGrant', 
               'Get-MgGroupPermissionGrantCount', 'Get-MgGroupPhoto', 
               'Get-MgGroupPhotoContent', 'Get-MgGroupRejectedSender', 
               'Get-MgGroupRejectedSenderByRef', 'Get-MgGroupRejectedSenderCount', 
               'Get-MgGroupSetting', 'Get-MgGroupSettingCount', 
               'Get-MgGroupSettingTemplateById', 'Get-MgGroupSettingTemplateCount', 
               'Get-MgGroupSettingTemplateDelta', 
               'Get-MgGroupSettingTemplateGroupSettingTemplate', 
               'Get-MgGroupSettingTemplateMemberGroup', 
               'Get-MgGroupSettingTemplateMemberObject', 
               'Get-MgGroupSiteActivityByInterval', 
               'Get-MgGroupSiteApplicableContentTypeForList', 
               'Get-MgGroupSiteByPath', 
               'Get-MgGroupSiteContentTypeCompatibleHubContentType', 
               'Get-MgGroupSiteDelta', 
               'Get-MgGroupSiteGetByPathApplicableContentTypeForList', 
               'Get-MgGroupSiteGetGraphBPrePathActivityByInterval', 
               'Get-MgGroupSiteListContentTypeCompatibleHubContentType', 
               'Get-MgGroupSiteListItemActivityByInterval', 
               'Get-MgGroupSiteListItemDelta', 
               'Get-MgGroupSitePageMicrosoftGraphSitePageCanvaLayoutHorizontalSectionColumnWebpartPositionOfWebPart', 
               'Get-MgGroupSitePageMicrosoftGraphSitePageCanvaLayoutVerticalSectionWebpartPositionOfWebPart', 
               'Get-MgGroupSitePageMicrosoftGraphSitePageWebPartPositionOfWebPart', 
               'Get-MgGroupThread', 'Get-MgGroupThreadCount', 
               'Get-MgGroupThreadPost', 'Get-MgGroupThreadPostAttachment', 
               'Get-MgGroupThreadPostAttachmentCount', 
               'Get-MgGroupThreadPostCount', 'Get-MgGroupThreadPostExtension', 
               'Get-MgGroupThreadPostExtensionCount', 
               'Get-MgGroupThreadPostInReplyToAttachment', 
               'Get-MgGroupThreadPostInReplyToAttachmentCount', 
               'Get-MgGroupThreadPostInReplyToExtension', 
               'Get-MgGroupThreadPostInReplyToExtensionCount', 
               'Get-MgGroupTransitiveMember', 
               'Get-MgGroupTransitiveMemberAsApplication', 
               'Get-MgGroupTransitiveMemberAsDevice', 
               'Get-MgGroupTransitiveMemberAsGroup', 
               'Get-MgGroupTransitiveMemberAsOrgContact', 
               'Get-MgGroupTransitiveMemberAsServicePrincipal', 
               'Get-MgGroupTransitiveMemberAsUser', 
               'Get-MgGroupTransitiveMemberCount', 
               'Get-MgGroupTransitiveMemberCountAsApplication', 
               'Get-MgGroupTransitiveMemberCountAsDevice', 
               'Get-MgGroupTransitiveMemberCountAsGroup', 
               'Get-MgGroupTransitiveMemberCountAsOrgContact', 
               'Get-MgGroupTransitiveMemberCountAsServicePrincipal', 
               'Get-MgGroupTransitiveMemberCountAsUser', 
               'Get-MgGroupTransitiveMemberOf', 
               'Get-MgGroupTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgGroupTransitiveMemberOfAsGroup', 
               'Get-MgGroupTransitiveMemberOfCount', 
               'Get-MgGroupTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgGroupTransitiveMemberOfCountAsGroup', 
               'Grant-MgGroupDriveItemPermission', 
               'Grant-MgGroupDriveRootPermission', 'Grant-MgGroupSitePermission', 
               'Invoke-MgAcceptGroupCalendarEvent', 
               'Invoke-MgAcceptGroupCalendarEventTentatively', 
               'Invoke-MgAcceptGroupEvent', 'Invoke-MgAcceptGroupEventTentatively', 
               'Invoke-MgCalendarGroupCalendar', 'Invoke-MgCheckinGroupDriveItem', 
               'Invoke-MgCheckinGroupDriveRoot', 'Invoke-MgCheckoutGroupDriveItem', 
               'Invoke-MgCheckoutGroupDriveRoot', 
               'Invoke-MgDeclineGroupCalendarEvent', 'Invoke-MgDeclineGroupEvent', 
               'Invoke-MgDismissGroupCalendarEventReminder', 
               'Invoke-MgDismissGroupEventReminder', 
               'Invoke-MgExtractGroupDriveItemSensitivityLabel', 
               'Invoke-MgExtractGroupDriveRootSensitivityLabel', 
               'Invoke-MgFollowGroupDriveItem', 'Invoke-MgFollowGroupDriveRoot', 
               'Invoke-MgForwardGroupCalendarEvent', 
               'Invoke-MgForwardGroupConversationThreadPost', 
               'Invoke-MgForwardGroupConversationThreadPostInReplyTo', 
               'Invoke-MgForwardGroupEvent', 'Invoke-MgForwardGroupThreadPost', 
               'Invoke-MgForwardGroupThreadPostInReplyTo', 'Invoke-MgGraphGroup', 
               'Invoke-MgGraphGroupDrive', 'Invoke-MgInviteGroupDriveItem', 
               'Invoke-MgInviteGroupDriveRoot', 'Invoke-MgPreviewGroupDriveItem', 
               'Invoke-MgPreviewGroupDriveRoot', 
               'Invoke-MgPreviewGroupOnenotePage', 
               'Invoke-MgReauthorizeGroupDriveItemSubscription', 
               'Invoke-MgReauthorizeGroupDriveListSubscription', 
               'Invoke-MgReauthorizeGroupDriveRootSubscription', 
               'Invoke-MgReauthorizeGroupSiteListSubscription', 
               'Invoke-MgRecentGroupDrive', 'Invoke-MgRenewGroup', 
               'Invoke-MgReplyGroupConversationThread', 
               'Invoke-MgReplyGroupConversationThreadPost', 
               'Invoke-MgReplyGroupConversationThreadPostInReplyTo', 
               'Invoke-MgReplyGroupThread', 'Invoke-MgReplyGroupThreadPost', 
               'Invoke-MgReplyGroupThreadPostInReplyTo', 
               'Invoke-MgRetryGroupServiceProvisioning', 
               'Invoke-MgSnoozeGroupCalendarEventReminder', 
               'Invoke-MgSnoozeGroupEventReminder', 
               'Invoke-MgSubscribeGroupByMail', 'Invoke-MgUnfollowGroupDriveItem', 
               'Invoke-MgUnfollowGroupDriveRoot', 
               'Join-MgGroupDriveListContentTypeWithHubSite', 
               'Join-MgGroupSiteContentTypeWithHubSite', 
               'Join-MgGroupSiteListContentTypeWithHubSite', 'New-MgGroup', 
               'New-MgGroupAcceptedSenderByRef', 'New-MgGroupConversation', 
               'New-MgGroupConversationThread', 
               'New-MgGroupConversationThreadPostAttachment', 
               'New-MgGroupConversationThreadPostAttachmentUploadSession', 
               'New-MgGroupConversationThreadPostExtension', 
               'New-MgGroupConversationThreadPostInReplyToAttachment', 
               'New-MgGroupConversationThreadPostInReplyToAttachmentUploadSession', 
               'New-MgGroupConversationThreadPostInReplyToExtension', 
               'New-MgGroupDriveItemLink', 'New-MgGroupDriveItemListItemLink', 
               'New-MgGroupDriveItemUploadSession', 'New-MgGroupDriveListItemLink', 
               'New-MgGroupDriveRootLink', 'New-MgGroupDriveRootListItemLink', 
               'New-MgGroupDriveRootUploadSession', 'New-MgGroupExtension', 
               'New-MgGroupLifecyclePolicy', 'New-MgGroupMember', 
               'New-MgGroupMemberByRef', 'New-MgGroupOwner', 'New-MgGroupOwnerByRef', 
               'New-MgGroupPermissionGrant', 'New-MgGroupRejectedSenderByRef', 
               'New-MgGroupSetting', 
               'New-MgGroupSettingTemplateGroupSettingTemplate', 
               'New-MgGroupSiteListItemLink', 'New-MgGroupThread', 
               'New-MgGroupThreadPostAttachment', 
               'New-MgGroupThreadPostAttachmentUploadSession', 
               'New-MgGroupThreadPostExtension', 
               'New-MgGroupThreadPostInReplyToAttachment', 
               'New-MgGroupThreadPostInReplyToAttachmentUploadSession', 
               'New-MgGroupThreadPostInReplyToExtension', 
               'Publish-MgGroupDriveListContentType', 
               'Publish-MgGroupSiteContentType', 
               'Publish-MgGroupSiteListContentType', 'Remove-MgGroup', 
               'Remove-MgGroupAcceptedSenderDirectoryObjectByRef', 
               'Remove-MgGroupByUniqueName', 'Remove-MgGroupConversation', 
               'Remove-MgGroupConversationThread', 
               'Remove-MgGroupConversationThreadPostAttachment', 
               'Remove-MgGroupConversationThreadPostExtension', 
               'Remove-MgGroupConversationThreadPostInReplyToAttachment', 
               'Remove-MgGroupConversationThreadPostInReplyToExtension', 
               'Remove-MgGroupDriveItemPermanent', 
               'Remove-MgGroupDriveRootPermanent', 'Remove-MgGroupExtension', 
               'Remove-MgGroupFavorite', 'Remove-MgGroupFromLifecyclePolicy', 
               'Remove-MgGroupLifecyclePolicy', 
               'Remove-MgGroupMemberDirectoryObjectByRef', 
               'Remove-MgGroupOwnerDirectoryObjectByRef', 
               'Remove-MgGroupPermissionGrant', 'Remove-MgGroupPhoto', 
               'Remove-MgGroupPhotoContent', 
               'Remove-MgGroupRejectedSenderDirectoryObjectByRef', 
               'Remove-MgGroupSetting', 
               'Remove-MgGroupSettingTemplateGroupSettingTemplate', 
               'Remove-MgGroupSite', 'Remove-MgGroupThread', 
               'Remove-MgGroupThreadPostAttachment', 
               'Remove-MgGroupThreadPostExtension', 
               'Remove-MgGroupThreadPostInReplyToAttachment', 
               'Remove-MgGroupThreadPostInReplyToExtension', 
               'Reset-MgGroupUnseenCount', 'Restore-MgGroupDriveItem', 
               'Restore-MgGroupDriveItemListItemDocumentSetVersion', 
               'Restore-MgGroupDriveItemListItemVersion', 
               'Restore-MgGroupDriveItemVersion', 
               'Restore-MgGroupDriveListItemDocumentSetVersion', 
               'Restore-MgGroupDriveListItemVersion', 'Restore-MgGroupDriveRoot', 
               'Restore-MgGroupDriveRootListItemDocumentSetVersion', 
               'Restore-MgGroupDriveRootListItemVersion', 
               'Restore-MgGroupDriveRootVersion', 'Restore-MgGroupSettingTemplate', 
               'Restore-MgGroupSiteListItemDocumentSetVersion', 
               'Restore-MgGroupSiteListItemVersion', 'Search-MgGroupDrive', 
               'Search-MgGroupDriveItem', 'Search-MgGroupDriveRoot', 
               'Set-MgGroupDriveItemSensitivityLabel', 
               'Set-MgGroupDriveRootSensitivityLabel', 'Set-MgGroupLicense', 
               'Set-MgGroupPhotoContent', 'Stop-MgGroupCalendarEvent', 
               'Stop-MgGroupEvent', 'Test-MgGroupDriveItemPermission', 
               'Test-MgGroupDriveListContentTypePublished', 
               'Test-MgGroupDriveRootPermission', 'Test-MgGroupProperty', 
               'Test-MgGroupSettingTemplateProperty', 
               'Test-MgGroupSiteContentTypePublished', 
               'Test-MgGroupSiteListContentTypePublished', 
               'Unpublish-MgGroupDriveListContentType', 
               'Unpublish-MgGroupSiteContentType', 
               'Unpublish-MgGroupSiteListContentType', 'Update-MgGroup', 
               'Update-MgGroupByUniqueName', 'Update-MgGroupConversationThread', 
               'Update-MgGroupConversationThreadPostExtension', 
               'Update-MgGroupConversationThreadPostInReplyToExtension', 
               'Update-MgGroupExtension', 'Update-MgGroupLifecyclePolicy', 
               'Update-MgGroupOnenotePageContent', 'Update-MgGroupPermissionGrant', 
               'Update-MgGroupSetting', 
               'Update-MgGroupSettingTemplateGroupSettingTemplate', 
               'Update-MgGroupThread', 'Update-MgGroupThreadPostExtension', 
               'Update-MgGroupThreadPostInReplyToExtension'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Remove-MgGroupAcceptedSenderByRef', 'Remove-MgGroupMemberByRef', 
               'Remove-MgGroupOwnerByRef', 'Remove-MgGroupRejectedSenderByRef'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoQwYJKoZIhvcNAQcCoIIoNDCCKDACAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAIAU6wVcXMnFoF
# J/2+RvMhVBIdsJLKS0WLJ4FMYTbohKCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGiMwghofAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEILaja1XSaKLdC/nrZVLBAHkb
# v0EFVBwGNiev91sMkQ5RMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAOuvdNsu4rVmXAt1bvFyjDHCtPTHm+b5MPWp0/A1ij8Gfr0fom//Y5w8Z
# 4APNAeQXd/Fec8XZ0uwDEg4d9llhK+3lTaLKiUf+A7j/nRsumufDxilKr/OcVLVa
# AMZajLxCo0GApSpRj3FgTZJzG69AX836Za6rHdAq+Kk5JzsMaU3N5E6UjCvKBdde
# XkAlZXKbgOxpi6+iygzKU5tZwUDJiw2xckRwVbOhmE73LXgt7746/t/aoeI4YKTD
# xSMQMrTmj05wA+LQYa8+d8Ei0F74gfjhMy+xhTJhdS1fM0Ce5AiApXud/7w8xYC0
# l7kaPDBWDv5JeePRFqfQ4SIKC9tjm6GCF60wghepBgorBgEEAYI3AwMBMYIXmTCC
# F5UGCSqGSIb3DQEHAqCCF4YwgheCAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFaBgsq
# hkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCBQlaLrD9Tnr2vCInXbciFrFNSAKgfMYMQox+1oc1R1aAIGZzvAHq5g
# GBMyMDI0MTEyMDE2NTg1Mi4zMDRaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo0MDFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaCCEfswggcoMIIFEKADAgECAhMzAAAB/tCowns0IQsBAAEAAAH+MA0G
# CSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI0
# MDcyNTE4MzExOFoXDTI1MTAyMjE4MzExOFowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9w
# ZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjQwMUEt
# MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvLwhFxWlqA43olsE4PCe
# gZ4mSfsH2YTSKEYv8Gn3362Bmaycdf5T3tQxpP3NWm62YHUieIQXw+0u4qlay4AN
# 3IonI+47Npi9fo52xdAXMX0pGrc0eqW8RWN3bfzXPKv07O18i2HjDyLuywYyKA9F
# mWbePjahf9Mwd8QgygkPtwDrVQGLyOkyM3VTiHKqhGu9BCGVRdHW9lmPMrrUlPWi
# YV9LVCB5VYd+AEUtdfqAdqlzVxA53EgxSqhp6JbfEKnTdcfP6T8Mir0HrwTTtV2h
# 2yDBtjXbQIaqycKOb633GfRkn216LODBg37P/xwhodXT81ZC2aHN7exEDmmbiWss
# jGvFJkli2g6dt01eShOiGmhbonr0qXXcBeqNb6QoF8jX/uDVtY9pvL4j8aEWS49h
# KUH0mzsCucIrwUS+x8MuT0uf7VXCFNFbiCUNRTofxJ3B454eGJhL0fwUTRbgyCbp
# LgKMKDiCRub65DhaeDvUAAJT93KSCoeFCoklPavbgQyahGZDL/vWAVjX5b8Jzhly
# 9gGCdK/qi6i+cxZ0S8x6B2yjPbZfdBVfH/NBp/1Ln7xbeOETAOn7OT9D3UGt0q+K
# iWgY42HnLjyhl1bAu5HfgryAO3DCaIdV2tjvkJay2qOnF7Dgj8a60KQT9QgfJfwX
# nr3ZKibYMjaUbCNIDnxz2ykCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBRvznuJ9SU2
# g5l/5/b+5CBibbHF3TAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
# BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmww
# bAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0El
# MjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
# BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEAiT4NUvO2lw+0
# dDMtsBuxmX2o3lVQqnQkuITAGIGCgI+sl7ZqZOTDd8LqxsH4GWCPTztc3tr8AgBv
# sYIzWjFwioCjCQODq1oBMWNzEsKzckHxAzYo5Sze7OPkMA3DAxVq4SSR8y+TRC2G
# cOd0JReZ1lPlhlPl9XI+z8OgtOPmQnLLiP9qzpTHwFze+sbqSn8cekduMZdLyHJk
# 3Niw3AnglU/WTzGsQAdch9SVV4LHifUnmwTf0i07iKtTlNkq3bx1iyWg7N7jGZAB
# RWT2mX+YAVHlK27t9n+WtYbn6cOJNX6LsH8xPVBRYAIRVkWsMyEAdoP9dqfaZzwX
# GmjuVQ931NhzHjjG+Efw118DXjk3Vq3qUI1re34zMMTRzZZEw82FupF3viXNR3DV
# OlS9JH4x5emfINa1uuSac6F4CeJCD1GakfS7D5ayNsaZ2e+sBUh62KVTlhEsQRHZ
# RwCTxbix1Y4iJw+PDNLc0Hf19qX2XiX0u2SM9CWTTjsz9SvCjIKSxCZFCNv/zpKI
# lsHx7hQNQHSMbKh0/wwn86uiIALEjazUszE0+X6rcObDfU4h/O/0vmbF3BMR+45r
# AZMAETJsRDPxHJCo/5XGhWdg/LoJ5XWBrODL44YNrN7FRnHEAAr06sflqZ8eeV3F
# uDKdP5h19WUnGWwO1H/ZjUzOoVGiV3gwggdxMIIFWaADAgECAhMzAAAAFcXna54C
# m0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZp
# Y2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMy
# MjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0B
# AQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51
# yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY
# 6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
# cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130/o5Tz9bshVZN
# 7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDua
# Rr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74
# kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2
# K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5
# TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
# i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
# BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3Pmri
# Lq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUC
# BBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJl
# pxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9y
# eS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUA
# YgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# 1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIw
# MTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/yp
# b+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulm
# ZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM
# 9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
# OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4
# FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3Uw
# xTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPX
# fx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVX
# VAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGC
# onsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
# 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
# ahC0HVUzWLOhcGbyoYIDVjCCAj4CAQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo0MDFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaIjCgEBMAcGBSsOAwIaAxUAhGNHD/a7Q0bQLWVG9JuGxgLRXseggYMw
# gYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsF
# AAIFAOroOL4wIhgPMjAyNDExMjAxMDMwMjJaGA8yMDI0MTEyMTEwMzAyMlowdDA6
# BgorBgEEAYRZCgQBMSwwKjAKAgUA6ug4vgIBADAHAgEAAgImczAHAgEAAgITPzAK
# AgUA6umKPgIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIB
# AAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQAVQh05owSD0vtZ
# FhuWpfnRzSj7YEP2NLTlKjHjrXrsNxiKQt8k0utLUbfxhglXDHh60Any1vIxHjHH
# uPxvnLPP/NWSWZ6lxhZDb22lejiH+9iORZTsSVTI44CSXS98dlJBVLTXnW3h8ywV
# 07GiQX5CUFT3JkzJ0orz+ZjI6AEgiD3wGe/4t8zTUPy7LaSUKLR241ocRx5MVk1H
# u8u6R/DfyCAIMXNp+RSt8S7HeAdArQC+IQQI9IbgvJCOWUqs6UoWqyrDDyfNqnWy
# 5wANrPGyB4Y5SH+Q0BaQBKFDn0LpXjjhVOZZV0fJjaa1FwkG/A3Jd1nAeLuFj22z
# pvgD257qMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTACEzMAAAH+0KjCezQhCwEAAQAAAf4wDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqG
# SIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgzXb3CW8N5nIJ
# pONex9gYQrnTJ23QbvCBI+5CUvp2k8IwgfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHk
# MIG9BCARhczd/FPInxjR92m2hPWqc+vGOG1+/I0WtkCstyh0eTCBmDCBgKR+MHwx
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
# Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB/tCowns0IQsBAAEAAAH+
# MCIEIACP8yZdE8UE4/AdlLtJfgPHAhTH39p2GQgcZt/hS4UFMA0GCSqGSIb3DQEB
# CwUABIICAAOUvyd7FdijCdPgWexNdNI4rklK0a+JD036P+XXh40j/PikLoyt46OH
# NC/HGYcH8xSc7BjlaqoTUGCAI2kMSs/eWfeLRx+m+OvQGUozckAZkXY4wcA2LWgy
# VANzVShcAg2GhEGAAtKBzezsP7KJ1O+g5/rZIe3BFLiTjv3ok2NQT5DkUCgEaSev
# vmZJDMokFHAeoN44Dhd8utdyyeiBBmlsWC9hugoptywy1uNQb9IahCq8tXiPA5L5
# MsKgKu8KpJys8BVNQZn2owinve0YxxfeFMxaVAayfHorRyYvRCkfJk9YZtMPG19b
# WM7W1iOdbFnSQ85HhkHXM9DAbFE2RibymbmAkHvN+LBEDW4WNLBNp99FlORGAMYo
# 2lNeyx82UH3f00OVTM1g2LywvbvHFj00CDmI16g/kxnCHekdZVUXvUqud2K3l0Dh
# fYg9t2B/ZZOCnVF5N40JboRtQ4v/R3CT6wN1B/UHBC7kZ1rGEnR2vpCxYfVUths4
# f/0et4d/7BseWvLgcTVZGVVd31D3dDur74pBA9DZLs/4rm6uqgIts6cEEL7/nA2W
# T1aG1i5vmyhV0iScbtIQB9sRMHCBcI4rmKRLygp83SsFnXe0C8JKoRg23Z8LEwV2
# tww1InU0yWu4AnYJlIi97EV0jckob1X9SpEyvJvxYH7KsCWc0P7C
# SIG # End signature block
