#
# Module manifest for module 'Microsoft.Graph.Identity.DirectoryManagement'
#
# Generated by: Microsoft Corporation
#
# Generated on: 11/20/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Identity.DirectoryManagement.psm1'

# Version number of this module.
ModuleVersion = '2.25.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'c767240d-585c-42cb-bb2f-6e76e6d639d4'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.25.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Identity.DirectoryManagement.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Identity.DirectoryManagement.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Confirm-MgContactMemberGroup', 'Confirm-MgContactMemberObject', 
               'Confirm-MgContractMemberGroup', 'Confirm-MgContractMemberObject', 
               'Confirm-MgDeviceMemberGroup', 'Confirm-MgDeviceMemberObject', 
               'Confirm-MgDirectoryDeletedItemMemberGroup', 
               'Confirm-MgDirectoryDeletedItemMemberObject', 
               'Confirm-MgDirectoryRoleMemberGroup', 
               'Confirm-MgDirectoryRoleMemberObject', 
               'Confirm-MgDirectoryRoleTemplateMemberGroup', 
               'Confirm-MgDirectoryRoleTemplateMemberObject', 'Confirm-MgDomain', 
               'Confirm-MgOrganizationMemberGroup', 
               'Confirm-MgOrganizationMemberObject', 'Get-MgAdminPeople', 
               'Get-MgAdminPeopleItemInsight', 
               'Get-MgAdminPeopleProfileCardProperty', 
               'Get-MgAdminPeopleProfileCardPropertyCount', 
               'Get-MgAdminPeoplePronoun', 'Get-MgContact', 'Get-MgContactById', 
               'Get-MgContactCount', 'Get-MgContactDelta', 
               'Get-MgContactDirectReport', 
               'Get-MgContactDirectReportAsOrgContact', 
               'Get-MgContactDirectReportAsUser', 'Get-MgContactDirectReportCount', 
               'Get-MgContactDirectReportCountAsOrgContact', 
               'Get-MgContactDirectReportCountAsUser', 'Get-MgContactManager', 
               'Get-MgContactMemberGroup', 'Get-MgContactMemberObject', 
               'Get-MgContactMemberOf', 
               'Get-MgContactMemberOfAsAdministrativeUnit', 
               'Get-MgContactMemberOfAsGroup', 'Get-MgContactMemberOfCount', 
               'Get-MgContactMemberOfCountAsAdministrativeUnit', 
               'Get-MgContactMemberOfCountAsGroup', 
               'Get-MgContactServiceProvisioningError', 
               'Get-MgContactServiceProvisioningErrorCount', 
               'Get-MgContactTransitiveMemberOf', 
               'Get-MgContactTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgContactTransitiveMemberOfAsGroup', 
               'Get-MgContactTransitiveMemberOfCount', 
               'Get-MgContactTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgContactTransitiveMemberOfCountAsGroup', 'Get-MgContract', 
               'Get-MgContractById', 'Get-MgContractCount', 'Get-MgContractDelta', 
               'Get-MgContractMemberGroup', 'Get-MgContractMemberObject', 
               'Get-MgDevice', 'Get-MgDeviceByDeviceId', 'Get-MgDeviceById', 
               'Get-MgDeviceCount', 'Get-MgDeviceDelta', 'Get-MgDeviceExtension', 
               'Get-MgDeviceExtensionCount', 'Get-MgDeviceMemberGroup', 
               'Get-MgDeviceMemberObject', 'Get-MgDeviceMemberOf', 
               'Get-MgDeviceMemberOfAsAdministrativeUnit', 
               'Get-MgDeviceMemberOfAsGroup', 'Get-MgDeviceMemberOfCount', 
               'Get-MgDeviceMemberOfCountAsAdministrativeUnit', 
               'Get-MgDeviceMemberOfCountAsGroup', 'Get-MgDeviceRegisteredOwner', 
               'Get-MgDeviceRegisteredOwnerAsAppRoleAssignment', 
               'Get-MgDeviceRegisteredOwnerAsEndpoint', 
               'Get-MgDeviceRegisteredOwnerAsServicePrincipal', 
               'Get-MgDeviceRegisteredOwnerAsUser', 
               'Get-MgDeviceRegisteredOwnerByRef', 
               'Get-MgDeviceRegisteredOwnerCount', 
               'Get-MgDeviceRegisteredOwnerCountAsAppRoleAssignment', 
               'Get-MgDeviceRegisteredOwnerCountAsEndpoint', 
               'Get-MgDeviceRegisteredOwnerCountAsServicePrincipal', 
               'Get-MgDeviceRegisteredOwnerCountAsUser', 
               'Get-MgDeviceRegisteredUser', 
               'Get-MgDeviceRegisteredUserAsAppRoleAssignment', 
               'Get-MgDeviceRegisteredUserAsEndpoint', 
               'Get-MgDeviceRegisteredUserAsServicePrincipal', 
               'Get-MgDeviceRegisteredUserAsUser', 
               'Get-MgDeviceRegisteredUserByRef', 
               'Get-MgDeviceRegisteredUserCount', 
               'Get-MgDeviceRegisteredUserCountAsAppRoleAssignment', 
               'Get-MgDeviceRegisteredUserCountAsEndpoint', 
               'Get-MgDeviceRegisteredUserCountAsServicePrincipal', 
               'Get-MgDeviceRegisteredUserCountAsUser', 
               'Get-MgDeviceTransitiveMemberOf', 
               'Get-MgDeviceTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgDeviceTransitiveMemberOfAsGroup', 
               'Get-MgDeviceTransitiveMemberOfCount', 
               'Get-MgDeviceTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgDeviceTransitiveMemberOfCountAsGroup', 'Get-MgDirectory', 
               'Get-MgDirectoryAdministrativeUnit', 
               'Get-MgDirectoryAdministrativeUnitCount', 
               'Get-MgDirectoryAdministrativeUnitDelta', 
               'Get-MgDirectoryAdministrativeUnitExtension', 
               'Get-MgDirectoryAdministrativeUnitExtensionCount', 
               'Get-MgDirectoryAdministrativeUnitMember', 
               'Get-MgDirectoryAdministrativeUnitMemberAsApplication', 
               'Get-MgDirectoryAdministrativeUnitMemberAsDevice', 
               'Get-MgDirectoryAdministrativeUnitMemberAsGroup', 
               'Get-MgDirectoryAdministrativeUnitMemberAsOrgContact', 
               'Get-MgDirectoryAdministrativeUnitMemberAsServicePrincipal', 
               'Get-MgDirectoryAdministrativeUnitMemberAsUser', 
               'Get-MgDirectoryAdministrativeUnitMemberByRef', 
               'Get-MgDirectoryAdministrativeUnitMemberCount', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsApplication', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsDevice', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsGroup', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsOrgContact', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsServicePrincipal', 
               'Get-MgDirectoryAdministrativeUnitMemberCountAsUser', 
               'Get-MgDirectoryAdministrativeUnitScopedRoleMember', 
               'Get-MgDirectoryAdministrativeUnitScopedRoleMemberCount', 
               'Get-MgDirectoryAttributeSet', 'Get-MgDirectoryAttributeSetCount', 
               'Get-MgDirectoryCustomSecurityAttributeDefinition', 
               'Get-MgDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'Get-MgDirectoryCustomSecurityAttributeDefinitionAllowedValueCount', 
               'Get-MgDirectoryCustomSecurityAttributeDefinitionCount', 
               'Get-MgDirectoryDeletedItem', 
               'Get-MgDirectoryDeletedItemAsAdministrativeUnit', 
               'Get-MgDirectoryDeletedItemAsApplication', 
               'Get-MgDirectoryDeletedItemAsDevice', 
               'Get-MgDirectoryDeletedItemAsGroup', 
               'Get-MgDirectoryDeletedItemAsServicePrincipal', 
               'Get-MgDirectoryDeletedItemAsUser', 
               'Get-MgDirectoryDeletedItemById', 
               'Get-MgDirectoryDeletedItemCountAsAdministrativeUnit', 
               'Get-MgDirectoryDeletedItemCountAsApplication', 
               'Get-MgDirectoryDeletedItemCountAsDevice', 
               'Get-MgDirectoryDeletedItemCountAsGroup', 
               'Get-MgDirectoryDeletedItemCountAsServicePrincipal', 
               'Get-MgDirectoryDeletedItemCountAsUser', 
               'Get-MgDirectoryDeletedItemMemberGroup', 
               'Get-MgDirectoryDeletedItemMemberObject', 
               'Get-MgDirectoryDeviceLocalCredential', 
               'Get-MgDirectoryDeviceLocalCredentialCount', 
               'Get-MgDirectoryFederationConfiguration', 
               'Get-MgDirectoryFederationConfigurationCount', 
               'Get-MgDirectoryOnPremiseSynchronization', 
               'Get-MgDirectoryOnPremiseSynchronizationCount', 
               'Get-MgDirectoryRole', 'Get-MgDirectoryRoleById', 
               'Get-MgDirectoryRoleByRoleTemplateId', 'Get-MgDirectoryRoleCount', 
               'Get-MgDirectoryRoleDelta', 'Get-MgDirectoryRoleMember', 
               'Get-MgDirectoryRoleMemberAsApplication', 
               'Get-MgDirectoryRoleMemberAsDevice', 
               'Get-MgDirectoryRoleMemberAsGroup', 
               'Get-MgDirectoryRoleMemberAsOrgContact', 
               'Get-MgDirectoryRoleMemberAsServicePrincipal', 
               'Get-MgDirectoryRoleMemberAsUser', 'Get-MgDirectoryRoleMemberByRef', 
               'Get-MgDirectoryRoleMemberCount', 
               'Get-MgDirectoryRoleMemberCountAsApplication', 
               'Get-MgDirectoryRoleMemberCountAsDevice', 
               'Get-MgDirectoryRoleMemberCountAsGroup', 
               'Get-MgDirectoryRoleMemberCountAsOrgContact', 
               'Get-MgDirectoryRoleMemberCountAsServicePrincipal', 
               'Get-MgDirectoryRoleMemberCountAsUser', 
               'Get-MgDirectoryRoleMemberGroup', 'Get-MgDirectoryRoleMemberObject', 
               'Get-MgDirectoryRoleScopedMember', 
               'Get-MgDirectoryRoleScopedMemberCount', 
               'Get-MgDirectoryRoleTemplate', 'Get-MgDirectoryRoleTemplateById', 
               'Get-MgDirectoryRoleTemplateCount', 
               'Get-MgDirectoryRoleTemplateDelta', 
               'Get-MgDirectoryRoleTemplateMemberGroup', 
               'Get-MgDirectoryRoleTemplateMemberObject', 
               'Get-MgDirectorySubscription', 
               'Get-MgDirectorySubscriptionByCommerceSubscriptionId', 
               'Get-MgDirectorySubscriptionCount', 'Get-MgDomain', 
               'Get-MgDomainCount', 'Get-MgDomainFederationConfiguration', 
               'Get-MgDomainFederationConfigurationCount', 
               'Get-MgDomainNameReference', 'Get-MgDomainNameReferenceCount', 
               'Get-MgDomainRootDomain', 'Get-MgDomainServiceConfigurationRecord', 
               'Get-MgDomainServiceConfigurationRecordCount', 
               'Get-MgDomainVerificationDnsRecord', 
               'Get-MgDomainVerificationDnsRecordCount', 'Get-MgOrganization', 
               'Get-MgOrganizationBranding', 
               'Get-MgOrganizationBrandingBackgroundImage', 
               'Get-MgOrganizationBrandingBannerLogo', 
               'Get-MgOrganizationBrandingCustomCss', 
               'Get-MgOrganizationBrandingFavicon', 
               'Get-MgOrganizationBrandingHeaderLogo', 
               'Get-MgOrganizationBrandingLocalization', 
               'Get-MgOrganizationBrandingLocalizationBackgroundImage', 
               'Get-MgOrganizationBrandingLocalizationBannerLogo', 
               'Get-MgOrganizationBrandingLocalizationCount', 
               'Get-MgOrganizationBrandingLocalizationCustomCss', 
               'Get-MgOrganizationBrandingLocalizationFavicon', 
               'Get-MgOrganizationBrandingLocalizationHeaderLogo', 
               'Get-MgOrganizationBrandingLocalizationSquareLogo', 
               'Get-MgOrganizationBrandingLocalizationSquareLogoDark', 
               'Get-MgOrganizationBrandingSquareLogo', 
               'Get-MgOrganizationBrandingSquareLogoDark', 
               'Get-MgOrganizationById', 'Get-MgOrganizationCount', 
               'Get-MgOrganizationExtension', 'Get-MgOrganizationExtensionCount', 
               'Get-MgOrganizationMemberGroup', 'Get-MgOrganizationMemberObject', 
               'Get-MgSubscribedSku', 'Get-MgUserScopedRoleMemberOf', 
               'Get-MgUserScopedRoleMemberOfCount', 
               'Invoke-MgAvailableDirectoryFederationConfigurationProviderType', 
               'Invoke-MgForceDomainDelete', 'Invoke-MgPromoteDomain', 
               'Invoke-MgRetryContactServiceProvisioning', 
               'New-MgAdminPeopleProfileCardProperty', 'New-MgContact', 
               'New-MgContract', 'New-MgDevice', 'New-MgDeviceExtension', 
               'New-MgDeviceRegisteredOwnerByRef', 
               'New-MgDeviceRegisteredUserByRef', 
               'New-MgDirectoryAdministrativeUnit', 
               'New-MgDirectoryAdministrativeUnitExtension', 
               'New-MgDirectoryAdministrativeUnitMember', 
               'New-MgDirectoryAdministrativeUnitMemberByRef', 
               'New-MgDirectoryAdministrativeUnitScopedRoleMember', 
               'New-MgDirectoryAttributeSet', 
               'New-MgDirectoryCustomSecurityAttributeDefinition', 
               'New-MgDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'New-MgDirectoryDeviceLocalCredential', 
               'New-MgDirectoryFederationConfiguration', 
               'New-MgDirectoryOnPremiseSynchronization', 'New-MgDirectoryRole', 
               'New-MgDirectoryRoleMemberByRef', 'New-MgDirectoryRoleScopedMember', 
               'New-MgDirectoryRoleTemplate', 'New-MgDirectorySubscription', 
               'New-MgDomain', 'New-MgDomainFederationConfiguration', 
               'New-MgDomainServiceConfigurationRecord', 
               'New-MgDomainVerificationDnsRecord', 'New-MgOrganization', 
               'New-MgOrganizationBrandingLocalization', 
               'New-MgOrganizationExtension', 'New-MgSubscribedSku', 
               'New-MgUserScopedRoleMemberOf', 'Remove-MgAdminPeopleItemInsight', 
               'Remove-MgAdminPeopleProfileCardProperty', 'Remove-MgContact', 
               'Remove-MgContract', 'Remove-MgDevice', 'Remove-MgDeviceByDeviceId', 
               'Remove-MgDeviceExtension', 
               'Remove-MgDeviceRegisteredOwnerDirectoryObjectByRef', 
               'Remove-MgDeviceRegisteredUserDirectoryObjectByRef', 
               'Remove-MgDirectoryAdministrativeUnit', 
               'Remove-MgDirectoryAdministrativeUnitExtension', 
               'Remove-MgDirectoryAdministrativeUnitMemberDirectoryObjectByRef', 
               'Remove-MgDirectoryAdministrativeUnitScopedRoleMember', 
               'Remove-MgDirectoryAttributeSet', 
               'Remove-MgDirectoryCustomSecurityAttributeDefinition', 
               'Remove-MgDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'Remove-MgDirectoryDeletedItem', 
               'Remove-MgDirectoryDeviceLocalCredential', 
               'Remove-MgDirectoryFederationConfiguration', 
               'Remove-MgDirectoryOnPremiseSynchronization', 
               'Remove-MgDirectoryRole', 'Remove-MgDirectoryRoleByRoleTemplateId', 
               'Remove-MgDirectoryRoleMemberDirectoryObjectByRef', 
               'Remove-MgDirectoryRoleScopedMember', 
               'Remove-MgDirectoryRoleTemplate', 'Remove-MgDirectorySubscription', 
               'Remove-MgDirectorySubscriptionByCommerceSubscriptionId', 
               'Remove-MgDomain', 'Remove-MgDomainFederationConfiguration', 
               'Remove-MgDomainServiceConfigurationRecord', 
               'Remove-MgDomainVerificationDnsRecord', 'Remove-MgOrganization', 
               'Remove-MgOrganizationBranding', 
               'Remove-MgOrganizationBrandingBackgroundImage', 
               'Remove-MgOrganizationBrandingBannerLogo', 
               'Remove-MgOrganizationBrandingCustomCss', 
               'Remove-MgOrganizationBrandingFavicon', 
               'Remove-MgOrganizationBrandingHeaderLogo', 
               'Remove-MgOrganizationBrandingLocalization', 
               'Remove-MgOrganizationBrandingLocalizationBackgroundImage', 
               'Remove-MgOrganizationBrandingLocalizationBannerLogo', 
               'Remove-MgOrganizationBrandingLocalizationCustomCss', 
               'Remove-MgOrganizationBrandingLocalizationFavicon', 
               'Remove-MgOrganizationBrandingLocalizationHeaderLogo', 
               'Remove-MgOrganizationBrandingLocalizationSquareLogo', 
               'Remove-MgOrganizationBrandingLocalizationSquareLogoDark', 
               'Remove-MgOrganizationBrandingSquareLogo', 
               'Remove-MgOrganizationBrandingSquareLogoDark', 
               'Remove-MgOrganizationExtension', 'Remove-MgSubscribedSku', 
               'Remove-MgUserScopedRoleMemberOf', 'Restore-MgDirectoryDeletedItem', 
               'Set-MgOrganizationBrandingBackgroundImage', 
               'Set-MgOrganizationBrandingBannerLogo', 
               'Set-MgOrganizationBrandingCustomCss', 
               'Set-MgOrganizationBrandingFavicon', 
               'Set-MgOrganizationBrandingHeaderLogo', 
               'Set-MgOrganizationBrandingLocalizationBackgroundImage', 
               'Set-MgOrganizationBrandingLocalizationBannerLogo', 
               'Set-MgOrganizationBrandingLocalizationCustomCss', 
               'Set-MgOrganizationBrandingLocalizationFavicon', 
               'Set-MgOrganizationBrandingLocalizationHeaderLogo', 
               'Set-MgOrganizationBrandingLocalizationSquareLogo', 
               'Set-MgOrganizationBrandingLocalizationSquareLogoDark', 
               'Set-MgOrganizationBrandingSquareLogo', 
               'Set-MgOrganizationBrandingSquareLogoDark', 
               'Set-MgOrganizationMobileDeviceManagementAuthority', 
               'Test-MgContactProperty', 'Test-MgContractProperty', 
               'Test-MgDeviceProperty', 'Test-MgDirectoryDeletedItemProperty', 
               'Test-MgDirectoryRoleProperty', 
               'Test-MgDirectoryRoleTemplateProperty', 
               'Test-MgOrganizationProperty', 'Update-MgAdminPeopleItemInsight', 
               'Update-MgAdminPeopleProfileCardProperty', 
               'Update-MgAdminPeoplePronoun', 'Update-MgContact', 
               'Update-MgContract', 'Update-MgDevice', 'Update-MgDeviceByDeviceId', 
               'Update-MgDeviceExtension', 'Update-MgDirectory', 
               'Update-MgDirectoryAdministrativeUnit', 
               'Update-MgDirectoryAdministrativeUnitExtension', 
               'Update-MgDirectoryAdministrativeUnitScopedRoleMember', 
               'Update-MgDirectoryAttributeSet', 
               'Update-MgDirectoryCustomSecurityAttributeDefinition', 
               'Update-MgDirectoryCustomSecurityAttributeDefinitionAllowedValue', 
               'Update-MgDirectoryDeviceLocalCredential', 
               'Update-MgDirectoryFederationConfiguration', 
               'Update-MgDirectoryOnPremiseSynchronization', 
               'Update-MgDirectoryRole', 'Update-MgDirectoryRoleByRoleTemplateId', 
               'Update-MgDirectoryRoleScopedMember', 
               'Update-MgDirectoryRoleTemplate', 'Update-MgDirectorySubscription', 
               'Update-MgDirectorySubscriptionByCommerceSubscriptionId', 
               'Update-MgDomain', 'Update-MgDomainFederationConfiguration', 
               'Update-MgDomainServiceConfigurationRecord', 
               'Update-MgDomainVerificationDnsRecord', 'Update-MgOrganization', 
               'Update-MgOrganizationBranding', 
               'Update-MgOrganizationBrandingLocalization', 
               'Update-MgOrganizationExtension', 'Update-MgSubscribedSku', 
               'Update-MgUserScopedRoleMemberOf'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-MgDirectoryDeletedAdministrativeUnit', 
               'Get-MgDirectoryDeletedApplication', 'Get-MgDirectoryDeletedDevice', 
               'Get-MgDirectoryDeletedGroup', 
               'Get-MgDirectoryDeletedServicePrincipal', 
               'Get-MgDirectoryDeletedUser', 'Remove-MgDeviceRegisteredOwnerByRef', 
               'Remove-MgDeviceRegisteredUserByRef', 
               'Remove-MgDirectoryAdministrativeUnitMemberByRef', 
               'Remove-MgDirectoryRoleMemberByRef'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoRgYJKoZIhvcNAQcCoIIoNzCCKDMCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCTxpG0igPDKWex
# UFqijTaoNcN9Kowt8LO67EIqgf/RFKCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGiYwghoiAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEID1fcBDxeskxqBjnJFGy7ZnV
# LIasj2Lbr3LBJhxrwcLNMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAESdymTtpHwZLomIMtf9Jb2oynIDHEivT38XtJ/bSQ80eYS0sMEChH96B
# NwN6b43zdGw9lsI1i7ToDK8DWmXEz5moSFmTlAMG3MnHJVnP1Li58T9IiGZykla1
# 1JjjymhtyO47wCfs3GgxpixotgJmJiG3h4T/mT6rwexgHhelPqgcmnufC7Yo0rl2
# 6lx3TJri0GlElsyyAyEpLjOeJ+055C155lEVkhntciPeKr5foabZktBCmCZHce9H
# vaFQzNNu1ZJw5T/GT2Jtyc21c4DcOCsQsOKR8dU7zq06LVlhvhZYQmsYY/CVperW
# NFwvyrwa08wZc9YnMbPfo8QxfV/yx6GCF7AwghesBgorBgEEAYI3AwMBMYIXnDCC
# F5gGCSqGSIb3DQEHAqCCF4kwgheFAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFaBgsq
# hkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCBEQn9xmoI7j+b+3TxGSROzk2NUdqAe+fYPYXvb2+GbogIGZzu+37vr
# GBMyMDI0MTEyMDE2NTkwOS4wNzVaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# TjozNjA1LTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaCCEf4wggcoMIIFEKADAgECAhMzAAAB91ggdQTK+8L0AAEAAAH3MA0G
# CSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI0
# MDcyNTE4MzEwNloXDTI1MTAyMjE4MzEwNlowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9w
# ZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjM2MDUt
# MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0OdHTBNom6/uXKaEKP9r
# PITkT6QxF11tjzB0Nk1byDpPrFTHha3hxwSdTcr8Y0a3k6EQlwqy6ROz42e0R5eD
# W+dCoQapipDIFUOYp3oNuqwX/xepATEkY17MyXFx6rQW2NcWUJW3Qo2AuJ0HOtbl
# SpItQZPGmHnGqkt/DB45Fwxk6VoSvxNcQKhKETkuzrt8U6DRccQm1FdhmPKgDzgc
# fDPM5o+GnzbiMu6y069A4EHmLMmkecSkVvBmcZ8VnzFHTDkGLdpnDV5FXjVObAgb
# SM0cnqYSGfRp7VGHBRqyoscvR4bcQ+CV9pDjbJ6S5rZn1uA8hRhj09Hs33HRevt4
# oWAVYGItgEsG+BrCYbpgWMDEIVnAgPZEiPAaI8wBGemE4feEkuz7TAwgkRBcUzLg
# Q4uvPqRD1A+Jkt26+pDqWYSn0MA8j0zacQk9q/AvciPXD9It2ez+mqEzgFRRsJGL
# tcf9HksvK8Jsd6I5zFShlqi5bpzf1Y4NOiNOh5QwW1pIvA5irlal7qFhkAeeeZqm
# op8+uNxZXxFCQG3R3s5pXW89FiCh9rmXrVqOCwgcXFIJQAQkllKsI+UJqGq9rmRA
# BJz5lHKTFYmFwcM52KWWjNx3z6odwz2h+sxaxewToe9GqtDx3/aU+yqNRcB8w0tS
# XUf+ylN4uk5xHEpLpx+ZNNsCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBTfRqQzP3m9
# PZWuLf1p8/meFfkmmDAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
# BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmww
# bAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0El
# MjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
# BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEAN0ajafILeL6S
# QIMIMAXM1Qd6xaoci2mOrpR8vKWyyTsL3b83A7XGLiAbQxTrqnXvVWWeNst5YQD8
# saO+UTgOLJdTdfUADhLXoK+RlwjfndimIJT9MH9tUYXLzJXKhZM09ouPwNsrn8YO
# LIpdAi5TPyN8Cl11OGZSlP9r8JnvomW00AoJ4Pl9rlg0G5lcQknAXqHa9nQdWp1Z
# xXqNd+0JsKmlR8tcANX33ClM9NnaClJExLQHiKeHUUWtqyLMl65TW6wRM7XlF7Y+
# PTnC8duNWn4uLng+ON/Z39GO6qBj7IEZxoq4o3avEh9ba43UU6TgzVZaBm8VaA0w
# SwUe/pqpTOYFWN62XL3gl/JC2pzfIPxP66XfRLIxafjBVXm8KVDn2cML9IvRK02s
# 941Y5+RR4gSAOhLiQQ6A03VNRup+spMa0k+XTPAi+2aMH5xa1Zjb/K8u9f9M05U0
# /bUMJXJDP++ysWpJbVRDiHG7szaca+r3HiUPjQJyQl2NiOcYTGV/DcLrLCBK2zG5
# 03FGb04N5Kf10XgAwFaXlod5B9eKh95PnXKx2LNBgLwG85anlhhGxxBQ5mFsJGkB
# n0PZPtAzZyfr96qxzpp2pH9DJJcjKCDrMmZziXazpa5VVN36CO1kDU4ABkSYTXOM
# 8RmJXuQm7mUF3bWmj+hjAJb4pz6hT5UwggdxMIIFWaADAgECAhMzAAAAFcXna54C
# m0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZp
# Y2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMy
# MjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0B
# AQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51
# yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY
# 6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
# cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130/o5Tz9bshVZN
# 7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDua
# Rr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74
# kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2
# K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5
# TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
# i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
# BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3Pmri
# Lq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUC
# BBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJl
# pxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9y
# eS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUA
# YgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# 1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIw
# MTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/yp
# b+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulm
# ZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM
# 9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
# OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4
# FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3Uw
# xTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPX
# fx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVX
# VAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGC
# onsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
# 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
# ahC0HVUzWLOhcGbyoYIDWTCCAkECAQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# TjozNjA1LTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaIjCgEBMAcGBSsOAwIaAxUAb28KDG/xXbNBjmM7/nqw3bgrEOaggYMw
# gYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsF
# AAIFAOroN38wIhgPMjAyNDExMjAxMDI1MDNaGA8yMDI0MTEyMTEwMjUwM1owdzA9
# BgorBgEEAYRZCgQBMS8wLTAKAgUA6ug3fwIBADAKAgEAAgIcwgIB/zAHAgEAAgIS
# 8zAKAgUA6umI/wIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAow
# CAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQCNNna1oXoq
# A6Z3AVwlFcRAslfeu/rJDsJ2Yw7mdLHUQZowu4REvuk7ybCc9BdXZL6NhxFM752C
# yuS8tEzAJ2oRxRlk4667J8AtMd8784omcvNvNXxZOAe/HB14iNGSCnq/EM+vnd82
# 0pxTnhF1KVyi9WjsxOESN0xkV5gr5vesF4trEzs3Lcz6DqMGaGXFkQBsvPrTTk6c
# +upzbL72qMjCLnzCRXk8sfE7mkhXGl6Mp/5MlAOPZY9pPomeSigDsYlx0BADPsFx
# rYm4gnPb2970lb266L2VvrR8Ox+oO9ptuiYVurl9gIhz5kx80tiL15cwCulotaCy
# dIZ28EKBZ6bgMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
# IDIwMTACEzMAAAH3WCB1BMr7wvQAAQAAAfcwDQYJYIZIAWUDBAIBBQCgggFKMBoG
# CSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgYnZirOgH
# CqCI6o+B5A69YnfZTl7azST8epIWd0aIeYswgfoGCyqGSIb3DQEJEAIvMYHqMIHn
# MIHkMIG9BCAh2pjaa3ca0ecYuhu60uYHP/IKnPbedbVQJ5SoIH5Z4jCBmDCBgKR+
# MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMT
# HU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB91ggdQTK+8L0AAEA
# AAH3MCIEIJa3To5fV97jyzuuChXO0+On8FzVLG0tIEHt5FgpiztjMA0GCSqGSIb3
# DQEBCwUABIICAG/cIpCqne1E3e1TiI1OXvemV242KO1FOKmO59tmdcHMg31XoTo1
# ehyIKlG6QAOHcyaMDUtSY7VuTD0XrIrqOTHmwKHBrhimbNpzvOK8MmPLKsUWl9Gt
# 8wdoZ6eIUsOcVWFxsJoNxgea40tKVfCJOz+0h4F1VlBmdLWjF2JlLn9jxSYsiiWT
# ZFp4o44B/xnEuWtSxJMSp0osk6gsZRqW8O84WWwWV4GTT57BFtsYv7aig/MYcpD0
# XDnXGZ4vHwQkKE32namyP5+B+CZGOx6+tyYJ/dcfZSKlxKPQUJTIV6zvv1b01QVQ
# NWCQkQz/pXKeeUfUnL1yY2qgEW2NOTTf4X5OGhGi3P03IxTt9ZJWepbADttoXHti
# lA518tIAKDk+qqCaWIbq3BBeLkuhjwFGnCOtCdcd1FNovp1wab1CpeEP/DvI2RhV
# T+Wg/7W/2zsdrz2dBH3+8Ug/86Z8Lw2GZ2cTpZfd4XEuvbhMqfvsWdIhThntbzRp
# wuU6WnjoRzdwlz7znPZh/XOe+dbmVMW1oIuRRLLeX/ESsZqnvKOwH++MkOdhXO6W
# pNma+kt3/JPrPOOb/vaBfI3Dl4ymScjSKyEeFMi+ffUGxetcU8vSIvfcShChkWwG
# VGs6H+MsoiDJXgbdirL7YRhA6tzoDyE/AFYh4IRQ0MjETkwQp0wvTbhD
# SIG # End signature block
